language: node_js
node_js:
 — “stable”
branches:
 only:
 — Dev
before_script:
 — npm install -g @ionic/cli
 — npm install 
 - npm ci
script:
 — ionic build 
after_success:
— rm -rf /tmp/MeuDinheiro
— && git clone  https://github.com/andreferreiratrindade/andreferreiratrindade.github.io.git  /tmp/MeuDinheiro/
— && cp -r www/* /tmp/MeuDinheiro/
— && cd /tmp/MeuDinheiro/
— && git config user.email "andreferreiratrindade@gmail.com"
— && git config user.name "André"
— && git add --all
— && git commit -a -m "deploy"
— && git checkout master
— && git remote add deploy "https://$GITHUB_TOKEN@github.com/andreferreiratrindade/andreferreiratrindade.github.io.git"
— && git push deploy master
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 github-token: $GITHUB_TOKEN
 on:
   branch: Dev
 local_dir: www